#' @eval options::as_params()
#' @name options_params
#'
NULL

#' Get Session (Slot) Data From A Databrary Volume By Session Name.
#'
#' @param this_session_name A string. The name of the target session. Defaults to "Advisory
#' Board Meeting", the name of several of the sessions in the public Volume 1.
#' @param vol_id An integer indicating the volume identifier. Default is 1.
#' @param rq An httr2 request, such as that generated by `make_default_request()`.
#'
#' @returns One or more JSON blobs (as lists) whose session name(s) match
#' `name` in the given volume.
#'
#' @inheritParams options_params
#'
#' @examples
#' \donttest{
#' \dontrun{
#' # Returns multiple JSON blobs with the name "Advisory Board Meeting" in Volume 1.
#' get_session_by_name()
#'
#' get_session_by_name(name = 'Top-level materials')
#' }
#' }
#' @export
get_session_by_name <-
  function(this_session_name = "Advisory Board Meeting",
           vol_id = 1,
           vb = options::opt("vb"),
           rq = NULL) {
    assertthat::is.string(this_session_name)
    assertthat::assert_that(length(this_session_name) == 1)
    
    assertthat::assert_that(is.numeric(vol_id))
    assertthat::assert_that(vol_id > 0)
    assertthat::assert_that(length(vol_id) == 1)
    
    assertthat::assert_that(is.logical(vb))
    assertthat::assert_that(length(vb) == 1)
    
    assertthat::assert_that(is.null(rq) |
                              ("httr2_request" %in% class(rq)))
    
    # if (is.null(rq)) {
    #   if (vb) {
    #     message("\nNULL request object. Will generate default.")
    #     message("Not logged in. Only public information will be returned.")
    #   }
    #   rq <- databraryr::make_default_request()
    # }
    # 
    # #--------------------------------------------------------------------------
    # extract_session_metadata <- function(volume_json) {
    #   assertthat::assert_that(is.list(volume_json))
    #   
    #   extract_single_session <- function(i, sessions) {
    #     this_session <- sessions$value[[i]]
    #     tibble::tibble(id = this_session$id,
    #                    top = this_session$top,
    #                    name = this_session$name)
    #   }
    #   
    #   these_sessions <- tibble::enframe(volume_json$containers)
    #   n_sessions <- dim(these_sessions)[1]
    #   purrr::map(1:n_sessions, extract_single_session, these_sessions) %>%
    #     purrr::list_rbind()
    # }
    # #--------------------------------------------------------------------------
    
    # rq <- rq %>%
    #   httr2::req_url(url = sprintf(GET_VOLUME_SESSIONS, vol_id, MAX_SESSIONS, PAGE_NUM))
    # 
    # if (vb)
    #   message("Retrieving session data for 'vol_id'= ",
    #           vol_id)
    # resp <- tryCatch(
    #   httr2::req_perform(rq),
    #   httr2_error = function(cnd)
    #     NULL
    # )
    # if (is.null(resp)) {
    #   message("Request URL: ", )
    #   message("Cannot access requested resource on Databrary. Exiting.")
    #   return(resp)
    # } else {
    #   these_sessions <- httr2::resp_body_json(resp)
    # }
    
    # volume_json <- NULL
    # volume_json <- get_volume_by_id(vol_id, vb, rq)
    # volume_sessions <- 
    # session_metadata <- list_volume_session_info(these_sessions)
    session_metadata <- list_volume_sessions(vol_id = vol_id,
                                             vb = vb,
                                             rq = rq)
    
    name <- NULL
    # name_matches <- dplyr::filter(session_metadata, 
    #                               session_name == this_session_name)
    name_matches <- dplyr::filter(session_metadata,
                                  stringr::str_detect(session_name, this_session_name))
    
    if (is.null(name_matches)) {
      message("No matches")
      return(NULL)
    }
    if (dim(name_matches)[1] == 0) {
      message("Empty array")
      return(NULL)
    }
    if (dim(name_matches)[1] > 1) {
      message("\nMultiple sessions with name '", this_session_name, "'.")
    }
    name_matches
    #purrr::map(name_matches$session_id, get_session_by_id, vol_id, rq = rq)
  }

# Helper function
extract_session_info <- function(x) {
  df = data.frame(vol_id = x$volume,
                  session_id = x$id,
                  session_name = x$name,
                  session_date = x$sourceDate,
                  release_lvl = x$releaseLevel,
                  n_files = x$fileCount)
  df
}