#' @eval options::as_params()
#' @name options_params
#'
NULL

#' Get Session Data From A Databrary Volume By Session Name.
#'
#' @param session_name A string. The name of the target session. Defaults to "Advisory
#' Board Meeting", the name of several of the sessions in the public Volume 1.
#' @param vol_id Volume identifier. Must be an integer. Default is 1.
#' @param vb Show verbose feedback. Defaults to `options::opt("vb")`.
#' @param rq An httr2 request, such as that generated by `make_default_request()`.
#'
#' @returns One or more JSON blobs (as lists) whose session name(s) match
#' `name` in the given volume.
#'
#' @inheritParams options_params
#'
#' @examples
#' \donttest{
#' \dontrun{
#' # Returns multiple JSON blobs with the name "Advisory Board Meeting" in Volume 1.
#' get_session_by_name()
#'
#' get_session_by_name(name = 'Top-level materials')
#' }
#' }
#' @export
get_session_by_name <-
  function(session_name = "Advisory Board Meeting",
           vol_id = 1,
           vb = options::opt("vb"),
           rq = NULL) {
    assertthat::assert_that(assertthat::is.string(session_name))
    assertthat::assert_that(length(session_name) == 1)
    assertthat::assert_that(!is.na(session_name))
    
    assertthat::assert_that(is.numeric(vol_id))
    assertthat::assert_that(vol_id > 0)
    assertthat::assert_that(length(vol_id) == 1)
    
    validate_flag(vb, "vb")
    
    assertthat::assert_that(is.null(rq) ||
                              inherits(rq, "httr2_request"))
    
    sessions <- collect_paginated_get(
      path = sprintf(API_VOLUME_SESSIONS, vol_id),
      params = list(search = session_name),
      rq = rq,
      vb = vb
    )
    
    if (is.null(sessions) || length(sessions) == 0) {
      if (vb)
        message("No sessions named '", session_name, "' in volume ", vol_id)
      return(NULL)
    }
    
    purrr::map(sessions, function(session) {
      databraryr::get_session_by_id(
        session_id = session$id,
        vol_id = vol_id,
        vb = vb,
        rq = rq
      )
    })
  }