#' Get Session (Slot) Data From A Databrary Volume By Session Name.
#' 
#' @param session_name A string. The name of the target session. Defaults to "Advisory
#' Board Meeting", the name of several of the sessions in the public Volume 1.
#' @param volume_json A JSON blob returned by `get_volume_by_id()`. If no
#' blob is provided, defaults to the value returned by `get_volume_by_id(vol_id = 1, rq)`
#' @rq An httr2 request, such as that generated by `make_default_request()`.
#' @returns One or more JSON blobs (as lists) whose session name(s) match 
#' `name` in the given volume.
#' @examples
#' @donttest{
#' @dontrun{
#' # Returns multiple JSON blobs with the name "Advisory Board Meeting" in Volume 1.
#' get_session_by_name() 
#' 
#' get_session_by_name(name = 'Top-level materials')
#' }
#' }
#' @export
get_session_by_name <-
  function(session_name = "Advisory Board Meeting",
           volume_json = get_volume_by_id(vol_id = 1, rq),
           rq) {
    
    assertthat::assert_that(is.list(volume_json))
    assertthat::is.string(session_name)
    if (is.null(rq)) {
      rq <- make_default_request()
    }
    
    session_metadata <- extract_session_metadata(volume_json) # Returns df
    
    name_matches <- dplyr::filter(session_metadata, name == session_name)
    
    if (is.null(name_matches)) {
      message("No matches")
      return(NULL)
    }
    if (dim(name_matches)[1] == 0) {
      message("Empty array")
      return(NULL)
    }
    if (dim(name_matches)[1] > 1) {
      message("Multiple sessions with name ", name, ".")
    }
    purrr::map(name_matches$id, get_session_by_id, volume_json, rq = rq)
  }